import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ContactFab from "../components/ContactFab";
import { LanguageProvider } from '@/contexts/LanguageContext';
import { cookies, headers } from 'next/headers';
import Header from "../components/Header";
import Footer from "../components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: 'Stitch Made Limited',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const headersList = await headers();

  let initialLanguage = 'en';

  // 1. Check Cookie (Highest priority)
  const languageCookie = cookieStore.get('language');
  if (languageCookie) {
    initialLanguage = languageCookie.value;
  } else {
    // 2. Check Accept-Language header
    const acceptLanguage = headersList.get('accept-language');
    if (acceptLanguage && acceptLanguage.includes('ja')) {
      initialLanguage = 'ja';
    }
  }

  return (
    <html lang={initialLanguage}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}>
        <LanguageProvider initialLanguage={initialLanguage}>
          <Header />
          {children}
          <ContactFab />
          <Footer />
        </LanguageProvider>
      </body>
    </html>
  )
}
